### ISSUE TITLE
macOS doesn't work

### ISSUE THREAD

**Issue by Helferino** [nkrapivin/NekoPresence#3] opened 2022-02-26 16:52 UTC
Hi, 

I tried NekoPresence's extension example in my project on MacBook M1 and it doesn't work. `np_initdiscord` is returning `false` but APP ID is correct. I even tried it on Windows (exactly same project) and it worked perfectly, so maybe there is problem with macOS ? M1 chip ? or some kind of macOS permission thing ?

**Comment by nkrapivin** [comment] 2022-03-01 17:03
That's a fun one.
GameMaker Studio 2 has an official native built M1 version, it will use that whenever possible.
Discord does not have an official M1 build, it is 'optimized' for Rosetta 2 (meaning it's been tested to work there), but it's still an AMD64 binary.
Since M1 macs are overly expensive I just can't afford one so I only built NekoPresence for AMD64.
Even if I were to build my extension for M1, Discord is still using Rosetta 2, there's no point.
You can probably force your app to run in Rosetta 2 as well or just... complain to Discord :/

**Comment by Helferino** [comment] 2022-03-01 17:51
Ah, so its M1 problem, ok that's I need to know. I'm using M1 just for development so it's not big deal at the end of day, I was just wondering.. thanks and yes, I will definitely complain to Discord >:(

**Comment by nkrapivin** [comment] 2022-05-28 15:46
I published a new 1.3.2 version, I did recompile the macOS library as Universal (took me an hour of my life to figure out how to force CMake to use the older SDK but build for ARM).
I have **no** idea if this will work with Discord itself, but my testing reports that it is a valid x86/M1 dylib and it does load & initialize for me on x86.

**Comment by nkrapivin** [comment] 2022-05-29 15:03
After some testing on an M1 Mac Mini it has been confirmed that NekoPresence now functions correctly on macOS, closing.

**Closed as completed by nkrapivin** 2022-05-29 15:03 UTC
